### PR TITLE
Add investment cost and capacity expansion calculations into notebook

### PR DESCRIPTION
**Pull request by yerbol-akhmetov**
Good day. Here I proposed to add investment cost calculations, as well as capacity expansion and optimal capacity calculations.

### CODE REVIEW

**Comment by GbotemiB** [comment]
Hello @yerbol-akhmetov, Thank you for the great work. 

I think this notebook should be a script instead, since there are no visuals in it. What do you think?

Also, i caught one typo in `get_generation_mix(n)` function. Should be `generations` instead of `generaions`

**Comment by yerbol-akhmetov** [comment]
> Hello @yerbol-akhmetov, Thank you for the great work.
> 
> Just a few comments
> 
> * I think this notebook should be a script instead, since there are no visuals in it. What do you think?
> * I caught one typo in `get_generation_mix(n)` function. Should be `generations` instead of `generaions`
> * I think the functions you have created will be better with a few docs strings to describe the functions.

Hi, @GbotemiB. Thanks for the review and comments. The purpose of this notebook was to help Bryan with code adaptation. I think it does not matter for him if it is script or notebook (maybe it is even faster to test with notebook). But I agree. I can convert it to script and add explanations to the functions. Thanks also for noting the typo. I will fix that. Yes, maybe these functions can be even placed into `_helpers.py`? What do you think? Although they will not be used within repo. Or I can create small script to test those functions and print results.

**Comment by yerbol-akhmetov** [comment]
Thanks, @GbotemiB. I have fixed the typo.

**Comment by GbotemiB** [comment]
Merging 🚀

**Comment by GbotemiB** [comment]
Merging 🚀

**Pull request merged**
